'use server'

import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'

export async function generateAuditToken(formData: FormData) {
    const membershipId = formData.get('membershipId') as string
    const year = parseInt(formData.get('year') as string)

    if (!membershipId || isNaN(year)) {
        throw new Error('Missing required fields')
    }

    const supabase = await createClient()

    // Get current admin user
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
        throw new Error('Unauthorized')
    }

    // Insert new audit log (token is auto-generated by DB default)
    const { error: insertError } = await supabase
        .from('annual_audits')
        .insert({
            membership_id: membershipId,
            year: year,
            status: 'pending'
        })

    if (insertError) {
        console.error('Error generating audit token:', insertError)
        throw new Error('Failed to generate audit request')
    }

    revalidatePath('/admin/audit')
}
